#include "recovery.h"
const char recovery_page[] =
"<!doctype html><html lang=en><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>OpenM1 Recovery</title><style>"
":root{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#17233b;background:#f4f7fb}"
"*{box-sizing:border-box}body{margin:0;padding:18px}main{max-width:700px;margin:auto}h1{margin:12px 0 0;font-size:32px}"
".sub{color:#66758c;margin:5px 0 20px}.card{background:white;border-radius:16px;padding:22px;margin:16px 0;box-shadow:0 6px 24px #18324b0b}"
".warn{background:#fff5e7;color:#784c0b;border-left:4px solid #eaa33a;padding:12px;border-radius:8px}"
".grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.item{background:#f5f8fc;padding:12px;border-radius:10px}"
"small{display:block;color:#768399;margin-bottom:4px}strong{overflow-wrap:anywhere}input{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}"
"button{background:#1769dd;color:white;border:0;border-radius:9px;padding:12px 16px;font:inherit;font-weight:600;margin-top:12px;cursor:pointer}"
"button:disabled{opacity:.5;cursor:wait}progress{width:100%;height:16px;margin:10px 0}#message{white-space:pre-wrap;overflow-wrap:anywhere;color:#44536a}"
"@media(max-width:500px){.grid{grid-template-columns:1fr}.card{padding:18px}}"
"</style><main><h1>OpenM1</h1><p class=sub>Phicomm M1 Open Firmware · Recovery v0.1.1</p>"
"<p class=warn>Recovery network is open. Do not expose this interface on an untrusted network.</p>"
"<section class=card><h2>Device</h2><div id=info class=grid>Loading…</div></section>"
"<section class=card><h2>Firmware upload</h2><p>Select a complete <code>*.ota.bin</code> file. The device checks its APP CRC and embedded MD5 before activating it.</p>"
"<input id=file type=file accept='.bin,.ota.bin,application/octet-stream'><div id=filemeta></div>"
"<button id=upload onclick='uploadFile()'>Start upgrade</button></section>"
"<section class=card><h2>Upgrade from URL</h2><p>The URL must be reachable from the device's current network. For example, connect your computer to the OpenM1-Recovery-XXXXXX network and serve a file from <code>http://192.168.4.2:8000/</code>. Public Internet is not available through this SoftAP.</p>"
"<input id=url type=url placeholder='http://192.168.4.2:8000/OpenM1.ota.bin'><button id=urlbutton onclick='upgradeUrl()'>Upgrade from URL</button></section>"
"<section class=card><h2>OTA status</h2><progress id=progress max=100 value=0></progress><div id=state>Idle</div><div id=message></div></section>"
"<section class=card><button onclick='reboot()'>Reboot device</button></section>"
"<script>const $=id=>document.getElementById(id);const labels={firmware:'Firmware',board:'Board',kernel:'Kernel',rf:'RF',mode:'Mode',ssid:'SSID',ip:'IP',uptime:'Uptime',free_heap:'Free Heap'};"
"async function update(){try{let i=await(await fetch('/api/info')).json();$('info').innerHTML=Object.entries(labels).map(([k,v])=>'<div class=item><small>'+v+'</small><strong>'+String(i[k]===undefined?'—':i[k])+'</strong></div>').join('');let s=await(await fetch('/api/ota/status')).json();$('state').textContent=s.state+' · '+s.progress+'% · Detected Kernel: '+(s.detected_kernel||'unknown');$('message').textContent=s.message||'';$('progress').value=s.progress;let busy=!['idle','failed'].includes(s.state);$('upload').disabled=busy;$('urlbutton').disabled=busy}catch(e){$('message').textContent='Device unreachable: '+e.message}}"
"$('file').onchange=()=>{let f=$('file').files[0];$('filemeta').textContent=f?f.name+' · '+f.size+' bytes':''};"
"async function uploadFile(){let f=$('file').files[0];if(!f){alert('Choose an OTA file');return}$('message').textContent='Uploading…';try{let r=await fetch('/api/ota/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f});$('message').textContent=(await r.json()).message}catch(e){$('message').textContent=e.message}update()}"
"async function upgradeUrl(){let u=$('url').value.trim();if(!u){alert('Enter an HTTP URL');return}try{let r=await fetch('/api/ota/url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:u})});$('message').textContent=(await r.json()).message}catch(e){$('message').textContent=e.message}update()}"
"async function reboot(){if(!confirm('Reboot device?'))return;await fetch('/api/reboot',{method:'POST'}).catch(()=>{});$('message').textContent='Rebooting…'}setInterval(update,500);update();</script></main></html>";
const size_t recovery_page_length = sizeof(recovery_page)-1;
