#!/usr/bin/env python3
import argparse
import hashlib
import json
from pathlib import Path
from ota_common import SDK_COMMIT, require_sdk_kernel
from verify_ota import verify

p = argparse.ArgumentParser()
p.add_argument('--ota', type=Path, required=True)
p.add_argument('--app', type=Path, required=True)
p.add_argument('--sdk-kernel', type=Path, required=True)
p.add_argument('--app-header-report', type=Path, required=True)
p.add_argument('--output', type=Path, required=True)
p.add_argument('--toolchain', required=True)
a = p.parse_args()
checks, details = verify(a.ota, a.sdk_kernel, a.app)
header = a.app_header_report.read_text()
header_valid = all(line.startswith('PASS ') for line in header.splitlines() if line.startswith(('PASS ', 'FAIL ')))
symbols_valid = all(f'PASS {symbol}' in header for symbol in ('user_handler','moc_app_main','moc_adapter','main'))
sdk_valid = Path('mico-os').is_dir() and __import__('subprocess').check_output(['git','-C','mico-os','rev-parse','HEAD'], text=True).strip() == SDK_COMMIT
kernel = require_sdk_kernel(a.sdk_kernel)
valid = all(checks.values()) and header_valid and symbols_valid and sdk_valid and '5.4.1' in a.toolchain
data = {'name':'OpenM1','firmware':'OpenM1','version':'0.6.4','board':'MK3080B','sdk_commit':SDK_COMMIT,
        'kernel':'3080B002.023','kernel_version':'3080B002.023','sdk_kernel_version':'3080B002.023',
        'kernel_source':'mico-os/resources/moc_kernel/3080B/kernel.bin',
        'kernel_sha256':hashlib.sha256(kernel).hexdigest(),'interface_version':3,
        'moc_app_header_valid':header_valid,'startup_symbols_valid':symbols_valid,
        'ota_format_valid':all(checks.values()),'kernel_app_same_sdk':sdk_valid,
        'safe_to_flash':valid,
        'boot_verified_on_hardware':True,
        'main_verified_on_hardware':True,
        'runtime_verified_on_hardware':True,
        'wifi_init_fix':'MicoInit before micoWlanPowerOn',
        'wifi_verified_on_hardware':True,
        'softap_verified_on_hardware':True,
        'http_verified_on_hardware':True,
        'ota_upload_verified_on_hardware':True,
        'ota_flash_write_verified_on_hardware':True,
        'ota_validation_verified_on_hardware':True,
        'ota_boot_table_verified_on_hardware':True,
        'ota_reboot_verified_on_hardware':True,
        'ota_bootloader_apply_verified_on_hardware':True,
        'ota_url_verified_on_hardware':False,
        'sta_feature_present':True,'sta_connect_supported':True,
        'sta_verified_on_hardware':True,
        'wifi_scan_feature_present':True,
        'wifi_scan_verified_on_hardware':False,
        'wifi_icon_feature_present':True,
        'wifi_icon_protocol_verified':True,
        'wifi_icon_control':'pwm',
        'wifi_icon_pwm':'MICO_PWM_5',
        'red_x_pwm':'MICO_PWM_4',
        'network_display_execution':'worker_thread',
        'network_display_uses_rtos_timer':False,
        'network_display_worker_stack':2048,
        'network_display_pwm_frequency_hz':50000,
        'network_display_pwm_duty_percent':20,
        'wifi_blink_interval_ms':150,
        'wifi_blink_phase_ms':150,
        'wifi_icon_protocol_reverse_verified':True,
        'wifi_icon_pwm_carrier_hardware_verified':True,
        'wifi_icon_blink_hardware_verified':True,
        'wifi_icon_solid_hardware_verified':True,
        'wifi_icon_hardware_verified':True,
        'wifi_icon_verified_on_hardware':True,
        'mqtt_feature_present':True,
        'mqtt_verified_on_hardware':False,
        'homeassistant_discovery_present':True,
        'homeassistant_discovery_verified_on_hardware':False,
        'mqtt_config_storage':'MiCO parameter partition app user data',
        'mqtt_worker_stack':6144,
        'sensor_uart_present':True,'sensor_uart_verified_on_hardware':True,
        'sensor_protocol_status':'partial','temperature_feature':True,
        'humidity_feature':True,'pm25_feature':True,'formaldehyde_feature':True,
        'sensor_values_verified_on_hardware':True,
        'sensor_uart':'MICO_UART_1','sensor_uart_tx_gpio':'GPIO9','sensor_uart_rx_gpio':'GPIO10',
        'sensor_uart_default_baud':115200,'sensor_uart_passive_rx_only':False,
        'sensor_uart_tx_init_command_present':False,
        'display_startup_sync_source':'reference zM1 firmware static disassembly',
        'display_startup_sync':'saved brightness and screen state',
        'web_ui_tabs':True,'web_ui_tabs_verified_on_hardware':False,
        'sensor_request_command_present':True,
        'sensor_request_command':'23 01 00 00 00 00 00 00 00 00 00 21',
        'sensor_request_source':'reference zM1 static disassembly',
        'sensor_request_verified_on_hardware':True,
        'sensor_auto_polling':True,
        'sensor_poll_interval_ms':2000,
        'web_sensor_refresh_interval_ms':2000,
        'brightness_feature_present':True,
        'brightness_protocol_verified':True,
        'brightness_levels':4,
        'brightness_verified_on_hardware':False,
        'network_health_present':True,
        'red_x_feature_present':True,
        'red_x_protocol_verified':True,
        'red_x_protocol_reverse_verified':True,
        'red_x_pwm_carrier_hardware_verified':True,
        'red_x_manual_hardware_verified':True,
        'red_x_hardware_verified':True,
        'red_x_verified_on_hardware':True,
        'no_internet_auto_red_x_hardware_verified':False,
        'wifi_credentials_persistent':True,
        'config_version':3,
        'wifi_auto_connect_supported':True,
        'ap_disable_after_sta_supported':True,
        'ap_auto_restore_on_sta_loss':True,
        'wifi_persistence_verified_on_hardware':False,
        'wifi_auto_connect_verified_on_hardware':False,
        'ap_auto_close_restore_verified_on_hardware':False,
        'wifi_control_architecture':'single_worker',
        'wifi_control_worker_stack':5120,
        'station_monitor_interval_ms':1000,
        'station_loss_threshold_samples':3,
        'station_ready_threshold_samples':2,
        'station_native_reconnect':True,
        'station_native_retry_interval_ms':5000,
        'station_native_reconnect_grace_ms':60000,
        'station_controlled_rearm':True,
        'station_controlled_rearm_min_interval_ms':60000,
        'separate_ap_policy_worker':False,
        'separate_station_supervisor_worker':False,
        'runtime_wlan_hal_single_owner':True,
        'station_status_cached':True,
        'manual_disconnect_pauses_runtime_reconnect':True,
        'boot_auto_connect_grace_ms':60000,
        'boot_recovery_only_window_ms':60000,
        'recovery_web_activity_hold_ms':15000,
        'ap_probe_interval_ms':5000,
        'ap_missing_threshold':3,
        'ap_restore_requires_debounce':True,
        'wifi_events_consumed_by_control_worker':True,
        'main_thread_released_after_boot':True,
        'housekeeping_stack_bytes':2048,
        'station_auto_connect_during_rescue_window':False,
        'physical_reflash_failsafe':True,
        'recovery_ap_real_state_probe':True,
        'recovery_ap_self_heal':True,
        'startup_subsystems_continue_if_ap_start_fails':True,
        'wifi_control_worker_hardware_verified':False,
        'cold_boot_hardware_verified':False,
        'station_long_run_hardware_verified':False,
        'ota_runtime_heap_preflight':True,
        'low_memory_safe_mode':True,
        'mqtt_lazy_worker':True,
        'cpu_stats_lazy_worker':True,
        'network_health_delayed_until_wifi_control':True,
        'wifi_ap_boot_failsafe_ms':120000,
        'wifi_ap_stable_before_close_ms':30000,
        'stack_overflow_notification_registered':True,
        'wifi_fault_notifications_registered':True,
        'station_one_time_rearm_after_ap_restore':True,
        'stack_usage_report_present':True,
        'cpu_usage_source':'low_priority_estimator',
        'cpu_usage_exact':False,
        'memory_stats_source':'MicoGetMemoryInfo',
        'flash_stats_source':'MicoFlashGetInfo',
        'flash_filesystem':False,
        'system_stats_verified_on_hardware':False,
        'display_frame_source_verified':True,
        'type0c_verified_on_hardware':True,
        'type0f_semantics':'brightness',
        'type18_response_enabled':False,
        'sensor_uart_response_verified_on_hardware':True,
        'sensor_uart_rx_ring_size':2048,'sensor_uart_worker_stack':4096,
        'recovery_ip':'192.168.4.1','recovery_ssid_format':'OpenM1-XXXXXX',
        'ota_partition_start':'0x00110000','ota_partition_size':741376,
        'hardware_verified':False,'toolchain':a.toolchain,
        'app_size':details['app_size'],'app_payload_size':details['payload_size'],
        'ota_size':details['size'],'app_crc16':details['crc16'],
        'ota_md5':details['md5'],'ota_sha256':details['sha256']}
a.output.write_text(json.dumps(data, indent=2)+'\n')
raise SystemExit(0 if valid else 1)
